#Deployment Example  with Recreate
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  namespace: jacocoworld4
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebappconnector
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebappconnector
    spec:
      containers:
      - name: javawebappcontainer
        image: agunuworld/java-web-app:8
        ports:
        - containerPort: 8080

---
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebappservicedeplyment                  #service name varies it can be any name
  namespace: jacocoworld4
spec:
  type: NodePort                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: javawebappconnector                                  #this selector helps to identify the label created in the pod
  ports:
  - port: 80                                                  #default
    targetPort: 8080    #target application of the pod app
    nodePort: 30037

~
