apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javawebapprs
  namespace: javawebappspace
spec:
  replicas: 2
  selector:
     matchLabels:
       app: javawebapp
       namespace: javawebappspace
  template:
    metadata:
        name: javawebapppod
        labels:
          app: javawebapp
          namespace: javawebappspace
    spec:
     containers:
     - name:  javawebappcontainer         #name of a container
       image:  agunuworld/java-web-app:8             #which images u want to create a container
       ports:
       - containerPort: 8080

---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice                             #service name varies it can be any name
  namespace: javawebappspace
spec:
  type: NodePort                                             #type of service and we have two types of services NodePortip and Notepod
  selector:
     app: javawebapp                     #this selector helps to identify the label created in the pod
  ports:
  - port: 80                                                  #default
    targetPort: 8080    #target application of the pod app
    nodePort: 30002

